defaults: &defaults
  twitter:
    consumer_key: <%= ENV["TWITTER_CS_KEY"] %>
    consumer_secret: <%= ENV["TWITTER_CS_SEC"] %>
    access_token_key: <%= ENV["TWITTER_AT_KEY"] %>
    access_token_secret: <%= ENV["TWITTER_AT_SEC"] %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
